name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    if: ${{ true }} 
    uses: annamalaiponnusamy/repo_02/.github/workflows/targetcalle.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
