name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  repository_dispatch:
   

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: json-output
           wait-for-completion-timeout: 30s
           wait-for-completion-interval: 20s
           display-workflow-run-url-interval: 20s
           display-workflow-run-url-timeout: 30s  
           wait-for-completion: true
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Another step that can handle the result
       id: trigger-step2
       if: always()
       run: |
            
            echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"            
            logs=$(echo ${{ steps.trigger-step.outputs.workflow-logs}})
            substring=$(echo "$logs" | grep -oP 'x.*?y')
            echo "Extracted substring: $substring"
            dup = $(echo "$substring" | sed -r ':a; s/\b([[:alnum:]]+)\b(.*)\b\1\b/\1\2/g; ta; s/(, )+/, /g; s/, *$//')
            cut="${dup:1:-1}" 
            echo $cut
    
 
          
