name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: output
           wait-for-completion-timeout: 1m
           wait-for-completion-interval: 20s
           display-workflow-run-url-interval: 20s
           display-workflow-run-url-timeout: 1m   
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Another step that can handle the result
       if: always()
       run: |
            echo 'run id :${{steps.trigger-step.outputs.workflow-logs}}' 
            echo 'run id :${{steps.trigger-step.outputs.workflow-id}}' 
            echo "workflow-conclusion id:${{ steps.trigger-step.outputs.workflow-conclusion }}"
            echo ${{ steps.trigger-step.outputs.firstword }} ${{ steps.trigger-step.outputs.secondword }}
        
  job2:
    runs-on: ubuntu-latest
    needs: job1    
    steps:      
      - run: |
          echo "run id : ${{  needs.job1.outputs.workflow-id }}" 
          echo "workflow-conclusion id : ${{ needs.job1.outputs.workflow-conclusion }}"
          echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
          
