
name: windows script check

on:
    workflow_dispatch:
    

jobs:
 example_job:
    name: Generate output
    runs-on: windows-latest 
    outputs:
     jobclusterstatus: ${{ steps.s3run.outputs.response-output1 }}
    steps:
             - name: Display Step Names
               run: |
                 runid = ${{ inputs.global-runid }} 
                 if ([string]::IsNullOrEmpty($runid)) {
                  $runid = "f"
                 }     
                  echo "runid"
                     
    
