name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  repository_dispatch:
   
permissions:
  actions: read
  contents: read

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
   
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ASPF_CLUSTER_CLEANER  }}
           workflow-logs: json-output
           wait-for-completion-timeout: 30s
           wait-for-completion-interval: 10s
           display-workflow-run-url-interval: 5s
           display-workflow-run-url-timeout: 5s  
           wait-for-completion: true
           inputs: >-
            {
            "run-name": "12345"
            }

     - name: Get Job Logs by Output
       id: get_job_names1
       shell: sh
       run: |
        curl -H "Authorization: Bearer ${{ secrets.ASPF_CLUSTER_CLEANER }}" \
         https://api.github.com/repos/annamalaiponnusamy/repo_02/actions/runs/${{ steps.trigger-step.outputs.workflow-id }}/jobs  > workflow_run.json \
               
     - name: Extract Step Names222
       run: |
              jq -r '.jobs[] | select(.name == "example_job") | .steps[].name' < workflow_run.json | tee step_names.txt
     - name: Remote Job Status2222
       id: joboutputstep
       run: |
                name=$(cat step_names.txt)
                IFS=' ' read -r -a splitNames <<< $name
                for item in ${splitNames[@]}; do
                  if [[ $item == Run echo* ]]; then
                    echo Run Item: $item
                  fi
                done
                  
     - name: Get Job Logs
       id: get_job_names
       run: |
        curl -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
        https://api.github.com/repos/annamalaiponnusamy/repo_02/actions/runs/${{ steps.trigger-step.outputs.workflow-id }}/jobs  > workflow_run.json \
        #| jq '.jobs[].steps[1].name' | tee step_names.txt 
        #| jq  '.jobs[] | select(.name == "Generate output") | .steps[].name' | tee step_names.txt
     - name: Extract Step Names
       run: |
        jq -r '.jobs[] | select(.name == "Generate output") | .steps[].name' < workflow_run.json | tee step_names.txt
    
     - name: Display Step Names
       run: |
        tr -d '"' < step_names.txt > step_names_no_quotes.txt
        name=$(cat step_names_no_quotes.txt)
        IFS=' ' read -r -a splitRunIdWithDate <<< "$name"
        echo "Run ID: ${splitRunIdWithDate[2]}" 
        echo "Step Names: $name"
            if [[ "${name}" == *"automationsuccess1"* ]]; then
            echo "response-output=pass" >> $GITHUB_OUTPUT  
            echo "pass"
            else
            echo "response-output=fail" >> $GITHUB_OUTPUT
             echo "fail"
            fi
            
           

     - name: Filter name from Step Names
       run: |
            stepName=$(sed -n '2p' step_names_no_quotes.txt)
            echo "The value of the 5th line is: $stepName"
            # Print the value
            IFS=',' read -r -a splitStepName <<< "$stepName"
            echo "Run ID: ${splitStepName[2]}"
            echo "response-output=${splitStepName[2]}" >> $GITHUB_OUTPUT

            str="   Hello, World!   "
            trimmed_str=$(echo "$str" | xargs)
            
            # Output the trimmed string
            echo "Original string: '$str'"
            echo "Trimmed string: '$trimmed_str'"
            echo "IsRecording: ${trimmed_str}"
            
     - name: Fetch remote job output
       run: |
           curl -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
                https://api.github.com/repos/annamalaiponnusamy/repo_02/actions/runs/${{ steps.trigger-step.outputs.workflow-id }}/jobs \
                 | jq '.jobs[] | select(.name == "example_job") | .steps[] | .outputs'
