name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: json-output
           wait-for-completion-timeout: 1m
           wait-for-completion-interval: 20s
           display-workflow-run-url-interval: 20s
           display-workflow-run-url-timeout: 1m   
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Another step that can handle the result
       if: always()
       run: echo '${{ fromJSON(steps.trigger-step.outputs.workflow-logs).my-remote-job }}'
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      
      - run: echo ${{  needs.job1.outputs.runid }} ${{ needs.job1.outputs.secondword }}
      - name: What is the event?
        run: |
          if [ ${{ needs.job1.outputs.firstword }} == 'pass' ]; then
            echo "This is a pass case event"          
          else
            echo "This is an unknown event"
          fi
          echo "Value of the global variable: ${{ env.MY_GLOBAL_VARIABLE }}"
