name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: annamalaiponnusamy/repo_01/.github/workflows/reusableworkflow.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: env.firstword == 'hello'
    steps:
      - run: echo ${{ env.firstword }} ${{ needs.job1.outputs.secondword }}
