name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v3
         - run: |
            echo "MY_VARIABLE=value1" >> $GITHUB_ENV
         - uses: annamalaiponnusamy/repo_01/.github/workflows/reusableworkflow.yml@main
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      
      - run: echo ${{  needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - name: What is the event?
        run: |
          if [ ${{ needs.job1.outputs.firstword }} == 'pass' ]; then
            echo "This is a pass case event"          
          else
            echo "This is an unknown event"
          fi
          echo "Value of the global variable: ${{ env.MY_GLOBAL_VARIABLE }}"
