name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: output
           wait-for-completion-timeout: 1m
           wait-for-completion-interval: 20s
           display-workflow-run-url-interval: 20s
           display-workflow-run-url-timeout: 1m           
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Another step that can handle the result
       id: trigger-step2
       if: always()
       run: |
            
            echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.id }}"
            echo "test" 
             
     - uses: actions/github-script@v7
       id: set-result
       with:
          script: |
            const string = ${{steps.trigger-step.outputs.workflow-logs}}
            words_with_x=$(echo "$string" | grep -o 'x[^x]*x')            
            result-encoding: string
     - name: Get result
       run: echo "$words_with_x"    
          
  job2:
    runs-on: ubuntu-latest
    needs: job1    
    steps:      
      - run: |          
          echo ${{ needs.job1.outputs.output1 }}
          
