name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: annamalaiponnusamy/repo_01/.github/workflows/reusableworkflow.yml@main

  job2:
   
    needs: job1
    if: needs.job1.outputs.firstword == 'hello123'
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
