name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: annamalaiponnusamy/repo_01/.github/workflows/reusableworkflow.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: output-artifact
      - name: Use the Output
        run: echo "The output value is:$(cat output_value)"
      - run: echo ${{  needs.job1.env.firstword }} ${{ needs.job1.outputs.secondword }}
