
name: Response check

on:
  workflow_dispatch:
  repository_dispatch:   

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step-runid
       uses: the-actions-org/workflow-dispatch@v4
       with:
          workflow: Get MoAutomation RunID
          repo: inContact/qa-aspf-config-check
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 5m
          wait-for-completion-interval: 20s
          display-workflow-run-url-interval: 20s
          display-workflow-run-url-timeout: 5m 
          wait-for-completion: true	  
    
             
   
	           
