name: response test

on:
  workflow_dispatch:
  repository_dispatch:
   

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: json-output
           wait-for-completion-timeout: 30s
           wait-for-completion-interval: 20s
           display-workflow-run-url-interval: 20s
           display-workflow-run-url-timeout: 30s  
           
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Another step that can handle the result
       id: trigger-step2
       if: always()
       run: |
            echo '${{ fromJSON(steps.trigger-step.outputs.workflow-logs).example_job }}'
            echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"  
            #echo "Another Workflow logs: ${{ steps.trigger-step.outputs.workflow-logs }}"  
            logs=$(echo ${{ steps.trigger-step.outputs.workflow-logs}})
            substring=$(echo "$logs" | grep -oP 'X.*?Y')
            echo "Extracted substring: $substring"
            #words=( $substring )
            #echo "$words"
            #word=$(echo "${words[0]}")
            # echo "$word"
            cut="${substring:1:-1}" 
            echo $cut
            echo "global-runid=12" >> $GITHUB_OUTPUT 
    
 
          
