name: response test

on:
  workflow_dispatch:
  repository_dispatch:
   

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Get MoAutomation RunID
           repo: inContact/qa-aspf-config-check
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: output
           wait-for-completion-timeout: 30s
           wait-for-completion-interval: 20s
           display-workflow-run-url-interval: 20s
           display-workflow-run-url-timeout: 30s  
           wait-for-completion: true
           inputs: >-
            {
            "run-name": "12345"
            }
     - name: Another step that can handle the result
       id: trigger-step2
       if: always()
       run: |
            
            echo "Another Workflow conclusion: ${{ steps.trigger-step-runid.outputs.workflow-conclusion }}"  
            echo "Another Workflow logs: ${{ steps.trigger-step-runid.outputs.workflow-logs }}"  
            logs=$(echo ${{ steps.trigger-step-runid.outputs.workflow-logs}})
            substring=$(echo "$logs" | grep -oP 'x.*?y')
            echo "Extracted substring: $substring"
            words=( $substring )
            echo "$words"
            word=$(echo "${words[0]}")
             echo "$word"
            cut="${word:1:-1}" 
            echo $cut
            echo "global-runid=12" >> $GITHUB_OUTPUT 
    
 
          
