name: test sCript

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: windows-latest
   
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository2       
       run: |
        $STATUS = 'pass'     
        echo "The status of application is: $STATUS" 
        if ($STATUS -match "pass") 
        {
          echo "pass"
        } 
        else 
        {
          echo "fail"
        }     
           
   
   
          
