name: test sCript

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step        
       run: |            
            input_string="Runid15"
            
            IFS=',' read -r -a string_split <<< "$input_string"
            
            #Print the split string
           
               echo "${string_split[0]}" 
               echo "${string_split[1]}"
               echo "${string_split[2]}"
             
            STATUS = "pass"     
            echo "The status of application is: $STATUS"             
            if [[ "${STATUS}" == *"pass"* ]]; then
             echo "pass""         
            else
             echo "fail"
            fi
   
   
          
