name: test sCript

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: windows-latest
   
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository2       
       run: |
        $STATUS = 'pass'     
        echo "The status of application is: $STATUS" 
        if ($STATUS -match "pass") 
        {
          echo "pass"
        } 
        else 
        {
          echo "fail"
        }    
   
     - name: Check for dotnet installation
       run: |
        dotnet --version
        if ($LASTEXITCODE -eq 0) {
          echo "dotnet is installed."
        } else {
            uses: actions/setup-dotnet@v3
            with:
            dotnet-version: 6.0.x
            echo "dotnet is installing now."
        }
       
     - name: Check for .NET Core
       run: |
        dotnet --version 2>&1 | findstr /i "Microsoft" > nul
        if %ERRORLEVEL% == 0 (
          echo ".NET Core is installed."
        ) else (
          echo ".NET Core is not installed."
        )
