name: test sCript

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step        
       run: |            
            input_string="Runid15"
            
            IFS=',' read -r -a string_split <<< "$input_string"
            
            #Print the split string
           
               echo "${string_split[0]}" 
               echo "${string_split[1]}"
               echo "${string_split[2]}"
      
     - name: Trigger the Workflow in auto gatling execution Repository2       
       run: |
        # Get the content of the file
        content=$(Get-Content "C:\Users\annamalai.ponnusamy\Projects\applicationoutput.txt")

        # Do something with the content
        echo "Application output:"
        echo "$content"

        # Example: Check if the output contains a specific string
        if ($content -match "pass") {
          echo "Success message found!"
        } else {
          echo "Success message not found."
        }         
           
   
   
          
