name: test sCript

on:
  workflow_dispatch:

jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps: 
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step        
       run: |            
            input_string="Runid15,2025-01-03 17:03,2025-01-03 17:05"
            IFS=$2 read -ra string_split <<< "$input_string"
            
            #Print the split string
           
               echo "${string_split[0]}" 
               echo "${string_split[1]}"
               echo "${string_split[2]}"
             
            
   
   
          
