name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow and scrap output
        id: trigger-step
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 5m
          wait-for-completion-interval: 30s
          display-workflow-run-url-interval: 30s
          display-workflow-run-url-timeout: 5m
          
      - name: Another step that can handle the result
        if: always()
        run: |
            echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"
            echo '${{ fromJSON(steps.trigger-step.outputs.workflow-logs).my-remote-job }}'
