name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypressrun:
    runs-on: ubuntu-latest
    outputs:
      logoutput: ${{ steps.logstep.outputs.log }}
      conclusionoutput: ${{ steps.conclusionstep.outputs.conclusion }}
    steps:
      - name: Invoke workflow and scrap output
        id: triggerstep
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 2m
          wait-for-completion-interval: 10s
          display-workflow-run-url-interval: 10s
          display-workflow-run-url-timeout: 2m 
      - name: Log step that can handle the result
        id: logstep
        if: contains(${{steps.triggerstep.outputs.workflow-logs}}, 'winsip3upsuccess')
        run:  echo "log=pass" >> $GITHUB_OUTPUT
      - name: Log step that can handle the result
        id: logstep2
        if:  ${{ ! contains(${{steps.triggerstep.outputs.workflow-logs}}, 'winsip3upsuccess') }}
        run:  echo "log=fail" >> $GITHUB_OUTPUT
      - name: Conclussion step that can handle the result
        id: conclusionstep        
        run:  echo "conclusion=${{ steps.triggerstep.outputs.workflow-conclusion }}" >> $GITHUB_OUTPUT
           
  cypress-run2:
        runs-on: ubuntu-latest 
        needs:  cypressrun
        if: needs.cypressrun.outputs.conclusionoutput == 'success'
        steps: 
        - name: Another step that can handle the result
          run: |
            echo ${{needs.cypressrun.outputs.conclusionoutput}}  
            echo ${{needs.cypressrun.outputs.logoutput}}  
             
         
  
