name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow and scrap output
        id: trigger-step
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 2m
          wait-for-completion-interval: 10s
          display-workflow-run-url-interval: 10s
          display-workflow-run-url-timeout: 2m
          
      - name: Another step that can handle the result
         
        if: contains('${{ fromJSON(steps.trigger-step.outputs.workflow-logs) }}', 'winsip3upsuccess')
        run: |
            
            echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"
            echo '${{ fromJSON(steps.trigger-step.outputs.workflow-logs).my-remote-job }}'
            echo '${{ steps.trigger-step.outputs.workflow-logs }}'
            echo '${{ fromJSON(steps.trigger-step.outputs.workflow-logs) }}'
            echo  contains('${{ steps.trigger-step.outputs.workflow-logs }}', 'winsip3upsuccess')
