name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow and scrap output
        id: trigger-step
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
      - name: Another step that can handle the result
        if: always()
        run: echo '${{ fromJSON(steps.trigger-step.outputs.workflow-logs).my-remote-job }}'
