name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypressrun:
    runs-on: ubuntu-latest
    outputs:
      log: ${{ steps.triggerstep.outputs.log }}
      conclusion: ${{ steps.triggerstep.outputs.conclusion }}
    steps:
      - name: Invoke workflow and scrap output
        id: triggerstep
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 2m
          wait-for-completion-interval: 10s
          display-workflow-run-url-interval: 10s
          display-workflow-run-url-timeout: 2m 
      - name: Another step that can handle the result
        if: always()
        run: |
            echo "Another Workflow conclusion: ${{ steps.triggerstep.outputs.workflow-conclusion }}"
            echo "log=${{ steps.triggerstep.outputs.workflow-logs }}" >> $GITHUB_OUTPUT
            echo "conclusion=${{ steps.triggerstep.outputs.workflow-conclusion }}" >> $GITHUB_OUTPUT
            
  cypress-run2:
        needs:  cypressrun
        if: ${{ needs.cypressrun.outputs.conclusion }} == 'success'
        runs-on: ubuntu-latest 
        steps: 
        - name: Another step that can handle the result
          run: |
            echo ${{needs.cypressrun.outputs.conclusion}}  
            echo ${{needs.cypressrun.outputs.log}}
          if: contains(needs.cypressrun.outputs.log, 'winsip3upsuccess')
        - name: handle-the-respoinse condition
          run: |
             echo "This step runs on success"     
  
