name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypressrun:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.triggerstep.outputs.count }}
      output2: ${{ steps.triggerstep.outputs.count }}
    steps:
      - name: Invoke workflow and scrap output
        id: triggerstep
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 2m
          wait-for-completion-interval: 10s
          display-workflow-run-url-interval: 10s
          display-workflow-run-url-timeout: 2m 
      - name: Another step that can handle the result
        if: always()
        run: |
            echo "Another Workflow conclusion: ${{ steps.triggerstep.outputs.workflow-conclusion }}"
            echo '${{ steps.triggerstep.outputs.workflow-logs }}'
            echo "count=${{ steps.triggerstep.outputs.workflow-conclusion }}" >> $GITHUB_OUTPUT
            
  cypress-run2:
        needs:  cypressrun
        if: ${{ needs.cypressrun.steps.trigger-step.outputs.workflow-conclusion }} == '11success'
        runs-on: ubuntu-latest 
        steps: 
        - name: Another step that can handle the result
          run: |
            echo "Another Workflow conclusion: ${{ needs.cypressrun.steps.trigger-step.outputs.workflow-conclusion }}"
            echo '${{ needs.cypressrun.trigger-step.outputs.workflow-logs }}'
            echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
             
