name: workflow_caller

on: 
    workflow_dispatch:
 
jobs:
  cypressrun:
    runs-on: ubuntu-latest
    outputs:
      logoutput: ${{ steps.triggerstep.outputs.log }}
      conclusionoutput: ${{ steps.triggerstep.outputs.conclusion }}
    steps:
      - name: Invoke workflow and scrap output
        id: triggerstep
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Another Workflow
          repo: annamalaiponnusamy/repo_02
          token: ${{ secrets.ACTIONS_KEY  }}
          workflow-logs: json-output
          wait-for-completion-timeout: 2m
          wait-for-completion-interval: 10s
          display-workflow-run-url-interval: 10s
          display-workflow-run-url-timeout: 2m 
      - name: Another step that can handle the result
        if: always()
        run: |
            
            echo "log=${{ steps.triggerstep.outputs.workflow-conclusion }}" >> $GITHUB_OUTPUT
            echo "conclusion=${{ steps.triggerstep.outputs.workflow-conclusion }}" >> $GITHUB_OUTPUT
            
  cypress-run2:
        needs:  cypressrun
        if: ${{ needs.cypressrun.outputs.conclusionoutput }} == 'success'
        runs-on: ubuntu-latest 
        steps: 
        - name: Another step that can handle the result
          run: |
            echo ${{needs.cypressrun.outputs.conclusionoutput}}  
            echo ${{needs.cypressrun.outputs.logoutput}}
         
  
