name: Run C# with Secrets on Self-Hosted Runner

on: 
    workflow_dispatch:
  

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # or your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run C# application with secrets
      run: dotnet run --project ./GithubSecretTest
      env:
        GITHUB_SECRET_USERNAME: ${{ secrets.GITHUB_SECRET_USERNAME }}
        GITHUB_SECRET_PASSWORD: ${{ secrets.GITHUB_SECRET_PASSWORD }}
