name: windows script check

on:
  workflow_dispatch:
  repository_dispatch:
   

jobs:
  job1:
   runs-on: windows-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
   
     - name: Trigger the Workflow in auto gatling execution Repository
       id: trigger-step
       uses: the-actions-org/workflow-dispatch@v4 
       with:
           workflow: Another Workflow
           repo: annamalaiponnusamy/repo_02
           token: ${{ secrets.ACTIONS_KEY  }}
           workflow-logs: json-output
           wait-for-completion-timeout: 30s
           wait-for-completion-interval: 10s
           display-workflow-run-url-interval: 10s
           display-workflow-run-url-timeout: 10s  
           wait-for-completion: true
           inputs: >-
            {
            "run-name": "12345"
            }     
    
     - name: Display Step Names
       run: |
        name = ""
        if ([string]::IsNullOrEmpty($runid)) {
         $runid = "f"
        }
        echo "runid"
        
                
        
     
          
