name: windows script check

on:
  workflow_call:
  workflow_dispatch:
   inputs:
    global-runid:
    description: 'The global rund for gatling report'
    required: false
    type: string
       

jobs:
  job1:
   runs-on: windows-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps: 
   
    
     - name: Display Step Names
       run: |
         runid = ${{ inputs.global-runid }} 
         if ([string]::IsNullOrEmpty($runid)) {
          $runid = "f"
         }     
          echo "runid"
        
                
        
     
          
