
name: windows script check

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    
  workflow_dispatch:
    inputs:
      run-name:
        description: 'The distinct run name used to retrieve the run ID. Defaults to the workflow name'
        type: string
        required: false

jobs:
 example_job:
    name: Generate output
    runs-on: windows-latest 
    outputs:
     jobclusterstatus: ${{ steps.s3run.outputs.response-output1 }}
    steps:
      - id: step1
        run: |
          echo "${{inputs.run-name}}"
           
      - name: Display Step Names
        run: |
         $runid = ${{ inputs.run-name }} 
         if ([string]::IsNullOrEmpty($runid)) {
          $runid = "f"
         }     
         echo "$runid"
         Write-Output "Run ID: $runid"
               
                     
    
